/**
 * Predefined DiceBear Avatar Configuration
 *
 * CodeJudge ships 20 pre-generated DiceBear avatars (12 male, 8 female).
 * These avatars are generated by the backend and served to the client purely
 * for selection — no customization, seed input, or generation happens here.
 *
 * URLs follow the same pattern used across CodeJudge (see leaderboard):
 * https://api.dicebear.com/7.x/avataaars/svg?seed={seed}
 */

export type AvatarGender = "male" | "female";

export interface PredefinedAvatar {
  /** Stable identifier, e.g. "male-1" */
  id: string;
  /** Display label, e.g. "Male 1" */
  label: string;
  gender: AvatarGender;
  /** DiceBear seed used to generate this avatar */
  seed: string;
  /** Fully-resolved pre-generated avatar URL */
  url: string;
}

/* =============================================
   Pre-generated avatar definitions
   ============================================= */

const API = "https://api.dicebear.com/7.x/avataaars/svg";

function buildAvatarUrl(seed: string): string {
  return `${API}?seed=${encodeURIComponent(seed)}`;
}

function makeAvatar(
  id: string,
  label: string,
  gender: AvatarGender,
  seed: string
): PredefinedAvatar {
  return { id, label, gender, seed, url: buildAvatarUrl(seed) };
}

/* ----- 12 Male Avatars ----- */

const MALE_AVATARS: PredefinedAvatar[] = [
  makeAvatar("male-1", "Male 1", "male", "AlexKing"),
  makeAvatar("male-2", "Male 2", "male", "RyanCole"),
  makeAvatar("male-3", "Male 3", "male", "DevShah"),
  makeAvatar("male-4", "Male 4", "male", "MaxPower"),
  makeAvatar("male-5", "Male 5", "male", "LeoNguyen"),
  makeAvatar("male-6", "Male 6", "male", "OmarKhan"),
  makeAvatar("male-7", "Male 7", "male", "SamBolt"),
  makeAvatar("male-8", "Male 8", "male", "JakeFrost"),
  makeAvatar("male-9", "Male 9", "male", "TomReed"),
  makeAvatar("male-10", "Male 10", "male", "EliStone"),
  makeAvatar("male-11", "Male 11", "male", "RajVerma"),
  makeAvatar("male-12", "Male 12", "male", "KaiLiu"),
];

/* ----- 8 Female Avatars ----- */

const FEMALE_AVATARS: PredefinedAvatar[] = [
  makeAvatar("female-1", "Female 1", "female", "MiaChen"),
  makeAvatar("female-2", "Female 2", "female", "AriaPatel"),
  makeAvatar("female-3", "Female 3", "female", "ZoeMartin"),
  makeAvatar("female-4", "Female 4", "female", "LilyWalsh"),
  makeAvatar("female-5", "Female 5", "female", "NoraBloom"),
  makeAvatar("female-6", "Female 6", "female", "IvyClark"),
  makeAvatar("female-7", "Female 7", "female", "MayaSingh"),
  makeAvatar("female-8", "Female 8", "female", "EvaHart"),
];

/* =============================================
   Exports
   ============================================= */

/** All 20 pre-generated avatars, ordered Male 1–12 then Female 1–8. */
export const PREDEFINED_AVATARS: PredefinedAvatar[] = [
  ...MALE_AVATARS,
  ...FEMALE_AVATARS,
];

/** Look up a pre-generated avatar by its stable id. */
export function getPredefinedAvatar(id: string | null | undefined): PredefinedAvatar | undefined {
  if (!id) return undefined;
  return PREDEFINED_AVATARS.find((a) => a.id === id);
}

/** Look up a pre-generated avatar by its URL. */
export function getPredefinedAvatarByUrl(url: string | null | undefined): PredefinedAvatar | undefined {
  if (!url) return undefined;
  return PREDEFINED_AVATARS.find((a) => a.url === url);
}