-- V2__create_and_seed_chapter_topics.sql
-- Creates chapter_topics and seeds topics for the B.Tech CSE subject chapters.
-- Requires subject_chapters(id, subject_id, chapter_name) to already exist.

BEGIN;

CREATE TABLE IF NOT EXISTS chapter_topics (
    id SERIAL PRIMARY KEY,
    chapter_id INTEGER NOT NULL,
    topic_name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_chapter_topics_chapter
        FOREIGN KEY (chapter_id)
        REFERENCES subject_chapters(id)
        ON DELETE CASCADE,

    CONSTRAINT uq_chapter_topics_chapter_topic
        UNIQUE (chapter_id, topic_name)
);

CREATE INDEX IF NOT EXISTS idx_chapter_topics_chapter_id
ON chapter_topics(chapter_id);

WITH topic_seed(subject_id, chapter_name, topic_name) AS (
    VALUES
    (15, 'Introduction to C Programming', 'History and Features of C'),
    (15, 'Introduction to C Programming', 'Structure of a C Program'),
    (15, 'Introduction to C Programming', 'Compilation and Execution'),
    (15, 'Introduction to C Programming', 'Input and Output Functions'),
    (15, 'Variables, Data Types and Operators', 'Variables and Constants'),
    (15, 'Variables, Data Types and Operators', 'Basic Data Types'),
    (15, 'Variables, Data Types and Operators', 'Type Conversion and Casting'),
    (15, 'Variables, Data Types and Operators', 'Arithmetic, Relational and Logical Operators'),
    (15, 'Decision Making and Control Statements', 'if and if-else Statements'),
    (15, 'Decision Making and Control Statements', 'Nested if and else-if Ladder'),
    (15, 'Decision Making and Control Statements', 'switch Statement'),
    (15, 'Decision Making and Control Statements', 'for, while and do-while Loops'),
    (15, 'Functions and Recursion', 'Function Declaration and Definition'),
    (15, 'Functions and Recursion', 'Parameter Passing'),
    (15, 'Functions and Recursion', 'Scope and Storage Classes'),
    (15, 'Functions and Recursion', 'Recursion'),
    (15, 'Arrays and Strings', 'One-Dimensional Arrays'),
    (15, 'Arrays and Strings', 'Two-Dimensional Arrays'),
    (15, 'Arrays and Strings', 'String Handling Functions'),
    (15, 'Arrays and Strings', 'Array and String Operations'),
    (15, 'Pointers', 'Pointer Basics'),
    (15, 'Pointers', 'Pointer Arithmetic'),
    (15, 'Pointers', 'Pointers and Arrays'),
    (15, 'Pointers', 'Pointers to Functions'),
    (15, 'Structures and Unions', 'Structures'),
    (15, 'Structures and Unions', 'Nested Structures'),
    (15, 'Structures and Unions', 'Unions'),
    (15, 'Structures and Unions', 'typedef and Enumerations'),
    (15, 'File Handling and Dynamic Memory Allocation', 'File Operations'),
    (15, 'File Handling and Dynamic Memory Allocation', 'Text and Binary Files'),
    (15, 'File Handling and Dynamic Memory Allocation', 'Dynamic Memory Allocation'),
    (15, 'File Handling and Dynamic Memory Allocation', 'Command Line Arguments'),
    (16, 'Introduction to Object-Oriented Programming', 'Procedural vs Object-Oriented Programming'),
    (16, 'Introduction to Object-Oriented Programming', 'Objects and Classes'),
    (16, 'Introduction to Object-Oriented Programming', 'OOP Principles'),
    (16, 'Introduction to Object-Oriented Programming', 'Message Passing'),
    (16, 'Classes and Objects', 'Class Definition'),
    (16, 'Classes and Objects', 'Object Creation'),
    (16, 'Classes and Objects', 'Member Functions'),
    (16, 'Classes and Objects', 'Access Specifiers'),
    (16, 'Constructors and Destructors', 'Default Constructor'),
    (16, 'Constructors and Destructors', 'Parameterized Constructor'),
    (16, 'Constructors and Destructors', 'Copy Constructor'),
    (16, 'Constructors and Destructors', 'Destructor'),
    (16, 'Inheritance', 'Single Inheritance'),
    (16, 'Inheritance', 'Multiple Inheritance'),
    (16, 'Inheritance', 'Multilevel Inheritance'),
    (16, 'Inheritance', 'Hierarchical and Hybrid Inheritance'),
    (16, 'Polymorphism', 'Function Overloading'),
    (16, 'Polymorphism', 'Operator Overloading'),
    (16, 'Polymorphism', 'Function Overriding'),
    (16, 'Polymorphism', 'Virtual Functions'),
    (16, 'Abstraction and Encapsulation', 'Data Abstraction'),
    (16, 'Abstraction and Encapsulation', 'Data Encapsulation'),
    (16, 'Abstraction and Encapsulation', 'Abstract Classes'),
    (16, 'Abstraction and Encapsulation', 'Interfaces'),
    (16, 'Exception Handling', 'Exception Basics'),
    (16, 'Exception Handling', 'try-catch Blocks'),
    (16, 'Exception Handling', 'Multiple Exception Handling'),
    (16, 'Exception Handling', 'User-Defined Exceptions'),
    (16, 'Templates and Generic Programming', 'Function Templates'),
    (16, 'Templates and Generic Programming', 'Class Templates'),
    (16, 'Templates and Generic Programming', 'Generic Programming'),
    (16, 'Templates and Generic Programming', 'Standard Template Library Basics'),
    (17, 'Introduction to Python', 'Python Features'),
    (17, 'Introduction to Python', 'Python Interpreter and Execution'),
    (17, 'Introduction to Python', 'Identifiers and Keywords'),
    (17, 'Introduction to Python', 'Input and Output'),
    (17, 'Variables, Data Types and Operators', 'Variables and Dynamic Typing'),
    (17, 'Variables, Data Types and Operators', 'Numeric Data Types'),
    (17, 'Variables, Data Types and Operators', 'Boolean and None Types'),
    (17, 'Variables, Data Types and Operators', 'Operators and Expressions'),
    (17, 'Conditional Statements and Loops', 'if Statements'),
    (17, 'Conditional Statements and Loops', 'if-elif-else'),
    (17, 'Conditional Statements and Loops', 'for Loop'),
    (17, 'Conditional Statements and Loops', 'while Loop and Loop Control'),
    (17, 'Functions and Recursion', 'Defining Functions'),
    (17, 'Functions and Recursion', 'Arguments and Return Values'),
    (17, 'Functions and Recursion', 'Lambda Functions'),
    (17, 'Functions and Recursion', 'Recursion'),
    (17, 'Strings', 'String Creation and Indexing'),
    (17, 'Strings', 'String Slicing'),
    (17, 'Strings', 'String Methods'),
    (17, 'Strings', 'String Formatting'),
    (17, 'Lists, Tuples, Sets and Dictionaries', 'Lists'),
    (17, 'Lists, Tuples, Sets and Dictionaries', 'Tuples'),
    (17, 'Lists, Tuples, Sets and Dictionaries', 'Sets'),
    (17, 'Lists, Tuples, Sets and Dictionaries', 'Dictionaries'),
    (17, 'Object-Oriented Programming in Python', 'Classes and Objects'),
    (17, 'Object-Oriented Programming in Python', 'Constructors'),
    (17, 'Object-Oriented Programming in Python', 'Inheritance'),
    (17, 'Object-Oriented Programming in Python', 'Polymorphism'),
    (17, 'File Handling, Modules and Exception Handling', 'File Reading and Writing'),
    (17, 'File Handling, Modules and Exception Handling', 'Modules and Packages'),
    (17, 'File Handling, Modules and Exception Handling', 'Exception Handling'),
    (17, 'File Handling, Modules and Exception Handling', 'Built-in and User-Defined Exceptions'),
    (18, 'Introduction to Java', 'Java Features'),
    (18, 'Introduction to Java', 'JDK, JRE and JVM'),
    (18, 'Introduction to Java', 'Java Program Structure'),
    (18, 'Introduction to Java', 'Compilation and Execution'),
    (18, 'Data Types, Variables and Operators', 'Primitive Data Types'),
    (18, 'Data Types, Variables and Operators', 'Variables and Constants'),
    (18, 'Data Types, Variables and Operators', 'Type Conversion'),
    (18, 'Data Types, Variables and Operators', 'Operators and Expressions'),
    (18, 'Control Statements', 'Conditional Statements'),
    (18, 'Control Statements', 'switch Statement'),
    (18, 'Control Statements', 'Loops'),
    (18, 'Control Statements', 'break and continue'),
    (18, 'Classes and Objects', 'Class Definition'),
    (18, 'Classes and Objects', 'Object Creation'),
    (18, 'Classes and Objects', 'Constructors'),
    (18, 'Classes and Objects', 'this and static Keywords'),
    (18, 'Inheritance and Polymorphism', 'Inheritance Types'),
    (18, 'Inheritance and Polymorphism', 'Method Overriding'),
    (18, 'Inheritance and Polymorphism', 'Method Overloading'),
    (18, 'Inheritance and Polymorphism', 'Dynamic Method Dispatch'),
    (18, 'Interfaces and Packages', 'Interfaces'),
    (18, 'Interfaces and Packages', 'Abstract Classes'),
    (18, 'Interfaces and Packages', 'Packages'),
    (18, 'Interfaces and Packages', 'Access Control'),
    (18, 'Exception Handling', 'Exception Hierarchy'),
    (18, 'Exception Handling', 'try-catch-finally'),
    (18, 'Exception Handling', 'throw and throws'),
    (18, 'Exception Handling', 'Custom Exceptions'),
    (18, 'Multithreading and Collections Framework', 'Thread Lifecycle'),
    (18, 'Multithreading and Collections Framework', 'Thread Synchronization'),
    (18, 'Multithreading and Collections Framework', 'List, Set and Map'),
    (18, 'Multithreading and Collections Framework', 'Iterators and Generics'),
    (19, 'Introduction to Data Structures', 'Data Structure Classification'),
    (19, 'Introduction to Data Structures', 'Abstract Data Types'),
    (19, 'Introduction to Data Structures', 'Time and Space Complexity'),
    (19, 'Introduction to Data Structures', 'Recursion Basics'),
    (19, 'Arrays and Matrices', 'Array Representation'),
    (19, 'Arrays and Matrices', 'Array Operations'),
    (19, 'Arrays and Matrices', 'Sparse Matrices'),
    (19, 'Arrays and Matrices', 'Multidimensional Arrays'),
    (19, 'Linked Lists', 'Singly Linked Lists'),
    (19, 'Linked Lists', 'Doubly Linked Lists'),
    (19, 'Linked Lists', 'Circular Linked Lists'),
    (19, 'Linked Lists', 'Linked List Applications'),
    (19, 'Stacks', 'Stack Operations'),
    (19, 'Stacks', 'Array and Linked Stack'),
    (19, 'Stacks', 'Expression Conversion'),
    (19, 'Stacks', 'Expression Evaluation'),
    (19, 'Queues', 'Queue Operations'),
    (19, 'Queues', 'Circular Queue'),
    (19, 'Queues', 'Priority Queue'),
    (19, 'Queues', 'Deque'),
    (19, 'Trees and Binary Search Trees', 'Tree Terminology'),
    (19, 'Trees and Binary Search Trees', 'Binary Trees'),
    (19, 'Trees and Binary Search Trees', 'Tree Traversals'),
    (19, 'Trees and Binary Search Trees', 'Binary Search Trees'),
    (19, 'Graphs', 'Graph Representation'),
    (19, 'Graphs', 'Breadth-First Search'),
    (19, 'Graphs', 'Depth-First Search'),
    (19, 'Graphs', 'Graph Applications'),
    (19, 'Hashing and Heaps', 'Hash Functions'),
    (19, 'Hashing and Heaps', 'Collision Resolution'),
    (19, 'Hashing and Heaps', 'Binary Heaps'),
    (19, 'Hashing and Heaps', 'Priority Queues using Heaps'),
    (20, 'Introduction to Algorithms', 'Characteristics of Algorithms'),
    (20, 'Introduction to Algorithms', 'Algorithm Design Process'),
    (20, 'Introduction to Algorithms', 'Correctness of Algorithms'),
    (20, 'Introduction to Algorithms', 'Algorithm Efficiency'),
    (20, 'Algorithm Analysis and Complexity', 'Asymptotic Notation'),
    (20, 'Algorithm Analysis and Complexity', 'Best, Average and Worst Case'),
    (20, 'Algorithm Analysis and Complexity', 'Time Complexity'),
    (20, 'Algorithm Analysis and Complexity', 'Space Complexity'),
    (20, 'Searching Algorithms', 'Linear Search'),
    (20, 'Searching Algorithms', 'Binary Search'),
    (20, 'Searching Algorithms', 'Interpolation Search'),
    (20, 'Searching Algorithms', 'Search Complexity'),
    (20, 'Sorting Algorithms', 'Bubble, Selection and Insertion Sort'),
    (20, 'Sorting Algorithms', 'Merge Sort'),
    (20, 'Sorting Algorithms', 'Quick Sort'),
    (20, 'Sorting Algorithms', 'Heap Sort'),
    (20, 'Divide and Conquer', 'Divide and Conquer Strategy'),
    (20, 'Divide and Conquer', 'Binary Search Analysis'),
    (20, 'Divide and Conquer', 'Merge Sort Analysis'),
    (20, 'Divide and Conquer', 'Quick Sort Analysis'),
    (20, 'Greedy Algorithms', 'Greedy Method'),
    (20, 'Greedy Algorithms', 'Activity Selection'),
    (20, 'Greedy Algorithms', 'Huffman Coding'),
    (20, 'Greedy Algorithms', 'Minimum Spanning Trees'),
    (20, 'Dynamic Programming', 'Dynamic Programming Principles'),
    (20, 'Dynamic Programming', 'Longest Common Subsequence'),
    (20, 'Dynamic Programming', 'Matrix Chain Multiplication'),
    (20, 'Dynamic Programming', 'Knapsack Problem'),
    (20, 'Graph Algorithms', 'BFS and DFS'),
    (20, 'Graph Algorithms', 'Dijkstra Algorithm'),
    (20, 'Graph Algorithms', 'Minimum Spanning Tree'),
    (20, 'Graph Algorithms', 'Topological Sorting'),
    (21, 'Algorithm Analysis and Asymptotic Notation', 'Big-O Notation'),
    (21, 'Algorithm Analysis and Asymptotic Notation', 'Omega and Theta Notation'),
    (21, 'Algorithm Analysis and Asymptotic Notation', 'Growth of Functions'),
    (21, 'Algorithm Analysis and Asymptotic Notation', 'Complexity Comparison'),
    (21, 'Recurrence Relations', 'Substitution Method'),
    (21, 'Recurrence Relations', 'Recursion Tree Method'),
    (21, 'Recurrence Relations', 'Master Theorem'),
    (21, 'Recurrence Relations', 'Solving Common Recurrences'),
    (21, 'Divide and Conquer', 'Merge Sort'),
    (21, 'Divide and Conquer', 'Quick Sort'),
    (21, 'Divide and Conquer', 'Binary Search'),
    (21, 'Divide and Conquer', 'Strassen Matrix Multiplication'),
    (21, 'Greedy Method', 'Greedy Choice Property'),
    (21, 'Greedy Method', 'Fractional Knapsack'),
    (21, 'Greedy Method', 'Huffman Coding'),
    (21, 'Greedy Method', 'Minimum Spanning Trees'),
    (21, 'Dynamic Programming', 'Optimal Substructure'),
    (21, 'Dynamic Programming', '0/1 Knapsack'),
    (21, 'Dynamic Programming', 'Longest Common Subsequence'),
    (21, 'Dynamic Programming', 'Floyd-Warshall Algorithm'),
    (21, 'Backtracking', 'Backtracking Method'),
    (21, 'Backtracking', 'N-Queens Problem'),
    (21, 'Backtracking', 'Graph Coloring'),
    (21, 'Backtracking', 'Hamiltonian Cycle'),
    (21, 'Branch and Bound', 'Branch and Bound Strategy'),
    (21, 'Branch and Bound', 'State Space Trees'),
    (21, 'Branch and Bound', 'Travelling Salesman Problem'),
    (21, 'Branch and Bound', '0/1 Knapsack using Branch and Bound'),
    (21, 'NP-Completeness and Approximation Algorithms', 'P and NP Classes'),
    (21, 'NP-Completeness and Approximation Algorithms', 'NP-Complete Problems'),
    (21, 'NP-Completeness and Approximation Algorithms', 'Polynomial-Time Reductions'),
    (21, 'NP-Completeness and Approximation Algorithms', 'Approximation Algorithms'),
    (22, 'Basic Computer Organization', 'Functional Units'),
    (22, 'Basic Computer Organization', 'Bus Structures'),
    (22, 'Basic Computer Organization', 'Stored Program Concept'),
    (22, 'Basic Computer Organization', 'Instruction Cycle'),
    (22, 'Data Representation and Computer Arithmetic', 'Number Systems'),
    (22, 'Data Representation and Computer Arithmetic', 'Signed Number Representation'),
    (22, 'Data Representation and Computer Arithmetic', 'Floating Point Representation'),
    (22, 'Data Representation and Computer Arithmetic', 'Arithmetic Algorithms'),
    (22, 'Register Transfer and Microoperations', 'Register Transfer Language'),
    (22, 'Register Transfer and Microoperations', 'Arithmetic Microoperations'),
    (22, 'Register Transfer and Microoperations', 'Logic Microoperations'),
    (22, 'Register Transfer and Microoperations', 'Shift Microoperations'),
    (22, 'Processor Organization', 'Register Organization'),
    (22, 'Processor Organization', 'Stack Organization'),
    (22, 'Processor Organization', 'Control Unit'),
    (22, 'Processor Organization', 'Microprogrammed Control'),
    (22, 'Instruction Set Architecture', 'Instruction Formats'),
    (22, 'Instruction Set Architecture', 'Addressing Modes'),
    (22, 'Instruction Set Architecture', 'RISC and CISC'),
    (22, 'Instruction Set Architecture', 'Instruction Execution'),
    (22, 'Memory Organization', 'Memory Hierarchy'),
    (22, 'Memory Organization', 'Cache Memory'),
    (22, 'Memory Organization', 'Main Memory'),
    (22, 'Memory Organization', 'Associative and Virtual Memory'),
    (22, 'Input Output Organization', 'I/O Interface'),
    (22, 'Input Output Organization', 'Programmed I/O'),
    (22, 'Input Output Organization', 'Interrupt-Driven I/O'),
    (22, 'Input Output Organization', 'Direct Memory Access'),
    (22, 'Pipelining and Parallel Processing', 'Instruction Pipelining'),
    (22, 'Pipelining and Parallel Processing', 'Pipeline Hazards'),
    (22, 'Pipelining and Parallel Processing', 'Parallel Processing'),
    (22, 'Pipelining and Parallel Processing', 'Multiprocessor Systems'),
    (25, 'Introduction to Operating Systems', 'Operating System Services'),
    (25, 'Introduction to Operating Systems', 'System Calls'),
    (25, 'Introduction to Operating Systems', 'Operating System Structures'),
    (25, 'Introduction to Operating Systems', 'Types of Operating Systems'),
    (25, 'Processes and Threads', 'Process Concept'),
    (25, 'Processes and Threads', 'Process States and PCB'),
    (25, 'Processes and Threads', 'Interprocess Communication'),
    (25, 'Processes and Threads', 'Threads and Multithreading'),
    (25, 'CPU Scheduling', 'Scheduling Criteria'),
    (25, 'CPU Scheduling', 'FCFS and SJF Scheduling'),
    (25, 'CPU Scheduling', 'Priority and Round Robin Scheduling'),
    (25, 'CPU Scheduling', 'Multilevel Queue Scheduling'),
    (25, 'Process Synchronization', 'Critical Section Problem'),
    (25, 'Process Synchronization', 'Mutex and Semaphores'),
    (25, 'Process Synchronization', 'Monitors'),
    (25, 'Process Synchronization', 'Classical Synchronization Problems'),
    (25, 'Deadlocks', 'Deadlock Conditions'),
    (25, 'Deadlocks', 'Resource Allocation Graph'),
    (25, 'Deadlocks', 'Deadlock Prevention and Avoidance'),
    (25, 'Deadlocks', 'Detection and Recovery'),
    (25, 'Memory Management', 'Contiguous Memory Allocation'),
    (25, 'Memory Management', 'Paging'),
    (25, 'Memory Management', 'Segmentation'),
    (25, 'Memory Management', 'Fragmentation'),
    (25, 'Virtual Memory', 'Demand Paging'),
    (25, 'Virtual Memory', 'Page Replacement Algorithms'),
    (25, 'Virtual Memory', 'Thrashing'),
    (25, 'Virtual Memory', 'Working Set Model'),
    (25, 'File Systems and I/O Management', 'File Concepts and Access Methods'),
    (25, 'File Systems and I/O Management', 'Directory Structures'),
    (25, 'File Systems and I/O Management', 'File Allocation Methods'),
    (25, 'File Systems and I/O Management', 'Disk and I/O Scheduling'),
    (27, 'Introduction to Computer Networks', 'Network Types'),
    (27, 'Introduction to Computer Networks', 'Network Topologies'),
    (27, 'Introduction to Computer Networks', 'Protocols and Standards'),
    (27, 'Introduction to Computer Networks', 'Network Devices'),
    (27, 'OSI and TCP/IP Models', 'OSI Reference Model'),
    (27, 'OSI and TCP/IP Models', 'TCP/IP Model'),
    (27, 'OSI and TCP/IP Models', 'Layered Architecture'),
    (27, 'OSI and TCP/IP Models', 'OSI vs TCP/IP'),
    (27, 'Physical Layer', 'Transmission Media'),
    (27, 'Physical Layer', 'Digital and Analog Signals'),
    (27, 'Physical Layer', 'Multiplexing'),
    (27, 'Physical Layer', 'Switching Techniques'),
    (27, 'Data Link Layer', 'Framing'),
    (27, 'Data Link Layer', 'Error Detection and Correction'),
    (27, 'Data Link Layer', 'Flow Control'),
    (27, 'Data Link Layer', 'MAC Protocols'),
    (27, 'Network Layer and Routing', 'IP Addressing'),
    (27, 'Network Layer and Routing', 'Subnetting'),
    (27, 'Network Layer and Routing', 'Routing Algorithms'),
    (27, 'Network Layer and Routing', 'IPv4 and IPv6'),
    (27, 'Transport Layer', 'TCP'),
    (27, 'Transport Layer', 'UDP'),
    (27, 'Transport Layer', 'Flow and Congestion Control'),
    (27, 'Transport Layer', 'Connection Management'),
    (27, 'Application Layer', 'DNS'),
    (27, 'Application Layer', 'HTTP and HTTPS'),
    (27, 'Application Layer', 'Email Protocols'),
    (27, 'Application Layer', 'FTP and Remote Login'),
    (27, 'Network Security and Wireless Networks', 'Cryptography Basics'),
    (27, 'Network Security and Wireless Networks', 'Firewalls'),
    (27, 'Network Security and Wireless Networks', 'Wireless LANs'),
    (27, 'Network Security and Wireless Networks', 'Network Attacks and Defense'),
    (28, 'Introduction to Software Engineering', 'Software Characteristics'),
    (28, 'Introduction to Software Engineering', 'Software Crisis'),
    (28, 'Introduction to Software Engineering', 'Software Engineering Principles'),
    (28, 'Introduction to Software Engineering', 'Software Process'),
    (28, 'Software Development Life Cycle', 'SDLC Phases'),
    (28, 'Software Development Life Cycle', 'Feasibility Study'),
    (28, 'Software Development Life Cycle', 'Development Activities'),
    (28, 'Software Development Life Cycle', 'Maintenance Activities'),
    (28, 'Software Process Models', 'Waterfall Model'),
    (28, 'Software Process Models', 'Incremental Model'),
    (28, 'Software Process Models', 'Spiral Model'),
    (28, 'Software Process Models', 'Agile Model'),
    (28, 'Requirements Engineering', 'Requirements Elicitation'),
    (28, 'Requirements Engineering', 'Functional and Non-Functional Requirements'),
    (28, 'Requirements Engineering', 'SRS'),
    (28, 'Requirements Engineering', 'Requirements Validation'),
    (28, 'Software Design', 'Design Principles'),
    (28, 'Software Design', 'Architectural Design'),
    (28, 'Software Design', 'Modular Design'),
    (28, 'Software Design', 'UML Diagrams'),
    (28, 'Software Testing', 'Testing Fundamentals'),
    (28, 'Software Testing', 'Black Box Testing'),
    (28, 'Software Testing', 'White Box Testing'),
    (28, 'Software Testing', 'Testing Levels'),
    (28, 'Software Project Management', 'Project Planning'),
    (28, 'Software Project Management', 'Effort Estimation'),
    (28, 'Software Project Management', 'Scheduling'),
    (28, 'Software Project Management', 'Risk Management'),
    (28, 'Software Maintenance and Quality Assurance', 'Software Maintenance Types'),
    (28, 'Software Maintenance and Quality Assurance', 'Software Quality'),
    (28, 'Software Maintenance and Quality Assurance', 'Quality Models'),
    (28, 'Software Maintenance and Quality Assurance', 'Configuration Management'),
    (29, 'Introduction to Automata Theory', 'Languages and Alphabets'),
    (29, 'Introduction to Automata Theory', 'Strings and Languages'),
    (29, 'Introduction to Automata Theory', 'Grammar Basics'),
    (29, 'Introduction to Automata Theory', 'Automata Models'),
    (29, 'Finite Automata', 'Deterministic Finite Automata'),
    (29, 'Finite Automata', 'Nondeterministic Finite Automata'),
    (29, 'Finite Automata', 'Epsilon-NFA'),
    (29, 'Finite Automata', 'DFA Minimization'),
    (29, 'Regular Expressions and Regular Languages', 'Regular Expressions'),
    (29, 'Regular Expressions and Regular Languages', 'Regular Grammars'),
    (29, 'Regular Expressions and Regular Languages', 'Closure Properties'),
    (29, 'Regular Expressions and Regular Languages', 'Pumping Lemma for Regular Languages'),
    (29, 'Context-Free Grammars', 'Context-Free Grammars'),
    (29, 'Context-Free Grammars', 'Parse Trees'),
    (29, 'Context-Free Grammars', 'Ambiguity'),
    (29, 'Context-Free Grammars', 'Normal Forms'),
    (29, 'Pushdown Automata', 'PDA Definition'),
    (29, 'Pushdown Automata', 'PDA Acceptance'),
    (29, 'Pushdown Automata', 'CFG and PDA Equivalence'),
    (29, 'Pushdown Automata', 'Deterministic PDA'),
    (29, 'Turing Machines', 'Turing Machine Model'),
    (29, 'Turing Machines', 'TM Variants'),
    (29, 'Turing Machines', 'Universal Turing Machine'),
    (29, 'Turing Machines', 'Church-Turing Thesis'),
    (29, 'Decidability and Undecidability', 'Decidable Languages'),
    (29, 'Decidability and Undecidability', 'Undecidable Problems'),
    (29, 'Decidability and Undecidability', 'Halting Problem'),
    (29, 'Decidability and Undecidability', 'Reductions'),
    (29, 'Complexity Theory', 'Time Complexity'),
    (29, 'Complexity Theory', 'Space Complexity'),
    (29, 'Complexity Theory', 'P and NP'),
    (29, 'Complexity Theory', 'NP-Completeness'),
    (30, 'Introduction to Compilers', 'Language Processing System'),
    (30, 'Introduction to Compilers', 'Compiler Phases'),
    (30, 'Introduction to Compilers', 'Compiler Passes'),
    (30, 'Introduction to Compilers', 'Compiler Tools'),
    (30, 'Lexical Analysis', 'Tokens, Lexemes and Patterns'),
    (30, 'Lexical Analysis', 'Regular Expressions'),
    (30, 'Lexical Analysis', 'Finite Automata in Lexical Analysis'),
    (30, 'Lexical Analysis', 'Lexical Analyzer Design'),
    (30, 'Syntax Analysis', 'Context-Free Grammars'),
    (30, 'Syntax Analysis', 'Parsing Basics'),
    (30, 'Syntax Analysis', 'Parse Trees'),
    (30, 'Syntax Analysis', 'Grammar Ambiguity'),
    (30, 'Top-Down Parsing', 'Recursive Descent Parsing'),
    (30, 'Top-Down Parsing', 'Predictive Parsing'),
    (30, 'Top-Down Parsing', 'FIRST and FOLLOW'),
    (30, 'Top-Down Parsing', 'LL(1) Parsing'),
    (30, 'Bottom-Up Parsing', 'Shift-Reduce Parsing'),
    (30, 'Bottom-Up Parsing', 'LR Parsing'),
    (30, 'Bottom-Up Parsing', 'SLR Parsing'),
    (30, 'Bottom-Up Parsing', 'LALR Parsing'),
    (30, 'Syntax-Directed Translation', 'Syntax-Directed Definitions'),
    (30, 'Syntax-Directed Translation', 'Attribute Grammars'),
    (30, 'Syntax-Directed Translation', 'Translation Schemes'),
    (30, 'Syntax-Directed Translation', 'Type Checking'),
    (30, 'Intermediate Code Generation', 'Three-Address Code'),
    (30, 'Intermediate Code Generation', 'Syntax Trees'),
    (30, 'Intermediate Code Generation', 'Quadruples and Triples'),
    (30, 'Intermediate Code Generation', 'Intermediate Representations'),
    (30, 'Code Optimization and Code Generation', 'Basic Blocks and Flow Graphs'),
    (30, 'Code Optimization and Code Generation', 'Local Optimization'),
    (30, 'Code Optimization and Code Generation', 'Global Optimization'),
    (30, 'Code Optimization and Code Generation', 'Target Code Generation'),
    (31, 'Introduction to Web Technologies', 'Internet and World Wide Web'),
    (31, 'Introduction to Web Technologies', 'Web Architecture'),
    (31, 'Introduction to Web Technologies', 'Web Browsers and Servers'),
    (31, 'Introduction to Web Technologies', 'URLs and HTTP'),
    (31, 'HTML', 'HTML Document Structure'),
    (31, 'HTML', 'Text and Formatting Tags'),
    (31, 'HTML', 'Tables and Lists'),
    (31, 'HTML', 'Forms and Semantic HTML'),
    (31, 'CSS', 'CSS Syntax and Selectors'),
    (31, 'CSS', 'Box Model'),
    (31, 'CSS', 'Layouts with Flexbox and Grid'),
    (31, 'CSS', 'Responsive Design'),
    (31, 'JavaScript', 'Variables and Data Types'),
    (31, 'JavaScript', 'Functions'),
    (31, 'JavaScript', 'Arrays and Objects'),
    (31, 'JavaScript', 'Events'),
    (31, 'DOM and Browser Programming', 'DOM Tree'),
    (31, 'DOM and Browser Programming', 'DOM Manipulation'),
    (31, 'DOM and Browser Programming', 'Event Handling'),
    (31, 'DOM and Browser Programming', 'Browser Storage'),
    (31, 'Client-Server Architecture', 'Client-Server Model'),
    (31, 'Client-Server Architecture', 'HTTP Request Response'),
    (31, 'Client-Server Architecture', 'Cookies and Sessions'),
    (31, 'Client-Server Architecture', 'Web Hosting Basics'),
    (31, 'Server-Side Web Development', 'Server-Side Programming'),
    (31, 'Server-Side Web Development', 'Routing'),
    (31, 'Server-Side Web Development', 'Templating'),
    (31, 'Server-Side Web Development', 'Database Connectivity'),
    (31, 'Web APIs, Security and Deployment', 'REST APIs'),
    (31, 'Web APIs, Security and Deployment', 'JSON and AJAX'),
    (31, 'Web APIs, Security and Deployment', 'Web Security Basics'),
    (31, 'Web APIs, Security and Deployment', 'Deployment and Hosting'),
    (33, 'Introduction to Computer Graphics', 'Applications of Computer Graphics'),
    (33, 'Introduction to Computer Graphics', 'Graphics Systems'),
    (33, 'Introduction to Computer Graphics', 'Raster and Vector Graphics'),
    (33, 'Introduction to Computer Graphics', 'Graphics Pipeline'),
    (33, 'Graphics Hardware and Display Devices', 'Raster Scan Displays'),
    (33, 'Graphics Hardware and Display Devices', 'Random Scan Displays'),
    (33, 'Graphics Hardware and Display Devices', 'Input Devices'),
    (33, 'Graphics Hardware and Display Devices', 'Frame Buffer'),
    (33, 'Line and Circle Drawing Algorithms', 'DDA Line Algorithm'),
    (33, 'Line and Circle Drawing Algorithms', 'Bresenham Line Algorithm'),
    (33, 'Line and Circle Drawing Algorithms', 'Midpoint Circle Algorithm'),
    (33, 'Line and Circle Drawing Algorithms', 'Ellipse Drawing'),
    (33, 'Two-Dimensional Transformations', 'Translation'),
    (33, 'Two-Dimensional Transformations', 'Rotation'),
    (33, 'Two-Dimensional Transformations', 'Scaling'),
    (33, 'Two-Dimensional Transformations', 'Composite Transformations'),
    (33, 'Three-Dimensional Transformations', '3D Translation'),
    (33, 'Three-Dimensional Transformations', '3D Rotation'),
    (33, 'Three-Dimensional Transformations', '3D Scaling'),
    (33, 'Three-Dimensional Transformations', '3D Composite Transformations'),
    (33, 'Viewing and Clipping', 'Viewing Pipeline'),
    (33, 'Viewing and Clipping', 'Window and Viewport'),
    (33, 'Viewing and Clipping', 'Line Clipping'),
    (33, 'Viewing and Clipping', 'Polygon Clipping'),
    (33, 'Curves and Surfaces', 'Bezier Curves'),
    (33, 'Curves and Surfaces', 'B-Spline Curves'),
    (33, 'Curves and Surfaces', 'Surface Representation'),
    (33, 'Curves and Surfaces', 'Fractals'),
    (33, 'Illumination, Shading and Hidden Surface Removal', 'Illumination Models'),
    (33, 'Illumination, Shading and Hidden Surface Removal', 'Gouraud Shading'),
    (33, 'Illumination, Shading and Hidden Surface Removal', 'Phong Shading'),
    (33, 'Illumination, Shading and Hidden Surface Removal', 'Hidden Surface Removal'),
    (34, 'Introduction to Artificial Intelligence', 'History and Scope of AI'),
    (34, 'Introduction to Artificial Intelligence', 'AI Approaches'),
    (34, 'Introduction to Artificial Intelligence', 'AI Applications'),
    (34, 'Introduction to Artificial Intelligence', 'Turing Test'),
    (34, 'Intelligent Agents', 'Agent and Environment'),
    (34, 'Intelligent Agents', 'Rational Agents'),
    (34, 'Intelligent Agents', 'Types of Agents'),
    (34, 'Intelligent Agents', 'PEAS Representation'),
    (34, 'Problem Solving and Search Techniques', 'State Space Search'),
    (34, 'Problem Solving and Search Techniques', 'Breadth-First and Depth-First Search'),
    (34, 'Problem Solving and Search Techniques', 'Uniform Cost Search'),
    (34, 'Problem Solving and Search Techniques', 'A* Search'),
    (34, 'Adversarial Search', 'Game Trees'),
    (34, 'Adversarial Search', 'Minimax Algorithm'),
    (34, 'Adversarial Search', 'Alpha-Beta Pruning'),
    (34, 'Adversarial Search', 'Evaluation Functions'),
    (34, 'Knowledge Representation', 'Propositional Logic'),
    (34, 'Knowledge Representation', 'First-Order Logic'),
    (34, 'Knowledge Representation', 'Semantic Networks'),
    (34, 'Knowledge Representation', 'Frames and Ontologies'),
    (34, 'Logical Reasoning and Inference', 'Inference Rules'),
    (34, 'Logical Reasoning and Inference', 'Forward Chaining'),
    (34, 'Logical Reasoning and Inference', 'Backward Chaining'),
    (34, 'Logical Reasoning and Inference', 'Resolution'),
    (34, 'Planning and Decision Making', 'Classical Planning'),
    (34, 'Planning and Decision Making', 'Planning Graphs'),
    (34, 'Planning and Decision Making', 'Decision Theory'),
    (34, 'Planning and Decision Making', 'Markov Decision Processes'),
    (34, 'Introduction to Machine Learning and AI Applications', 'Supervised Learning'),
    (34, 'Introduction to Machine Learning and AI Applications', 'Unsupervised Learning'),
    (34, 'Introduction to Machine Learning and AI Applications', 'Natural Language Processing'),
    (34, 'Introduction to Machine Learning and AI Applications', 'Computer Vision'),
    (35, 'Introduction to Machine Learning', 'Types of Machine Learning'),
    (35, 'Introduction to Machine Learning', 'Machine Learning Workflow'),
    (35, 'Introduction to Machine Learning', 'Training and Testing Data'),
    (35, 'Introduction to Machine Learning', 'Bias and Variance'),
    (35, 'Data Preprocessing and Feature Engineering', 'Missing Data Handling'),
    (35, 'Data Preprocessing and Feature Engineering', 'Encoding Categorical Data'),
    (35, 'Data Preprocessing and Feature Engineering', 'Feature Scaling'),
    (35, 'Data Preprocessing and Feature Engineering', 'Feature Selection'),
    (35, 'Linear Regression', 'Simple Linear Regression'),
    (35, 'Linear Regression', 'Multiple Linear Regression'),
    (35, 'Linear Regression', 'Cost Function'),
    (35, 'Linear Regression', 'Gradient Descent'),
    (35, 'Classification Algorithms', 'Logistic Regression'),
    (35, 'Classification Algorithms', 'K-Nearest Neighbors'),
    (35, 'Classification Algorithms', 'Support Vector Machines'),
    (35, 'Classification Algorithms', 'Naive Bayes'),
    (35, 'Decision Trees and Ensemble Methods', 'Decision Trees'),
    (35, 'Decision Trees and Ensemble Methods', 'Random Forest'),
    (35, 'Decision Trees and Ensemble Methods', 'Bagging'),
    (35, 'Decision Trees and Ensemble Methods', 'Boosting'),
    (35, 'Clustering Algorithms', 'K-Means Clustering'),
    (35, 'Clustering Algorithms', 'Hierarchical Clustering'),
    (35, 'Clustering Algorithms', 'DBSCAN'),
    (35, 'Clustering Algorithms', 'Cluster Evaluation'),
    (35, 'Model Evaluation and Validation', 'Train-Test Split'),
    (35, 'Model Evaluation and Validation', 'Cross Validation'),
    (35, 'Model Evaluation and Validation', 'Classification Metrics'),
    (35, 'Model Evaluation and Validation', 'Regression Metrics'),
    (35, 'Dimensionality Reduction and Neural Networks', 'Principal Component Analysis'),
    (35, 'Dimensionality Reduction and Neural Networks', 'Linear Discriminant Analysis'),
    (35, 'Dimensionality Reduction and Neural Networks', 'Neural Network Basics'),
    (35, 'Dimensionality Reduction and Neural Networks', 'Backpropagation'),
    (67, 'Introduction to Software Testing', 'Testing Objectives'),
    (67, 'Introduction to Software Testing', 'Verification and Validation'),
    (67, 'Introduction to Software Testing', 'Testing Principles'),
    (67, 'Introduction to Software Testing', 'Software Defects'),
    (67, 'Software Testing Life Cycle', 'Requirement Analysis'),
    (67, 'Software Testing Life Cycle', 'Test Planning'),
    (67, 'Software Testing Life Cycle', 'Test Case Development'),
    (67, 'Software Testing Life Cycle', 'Test Closure'),
    (67, 'Black Box Testing', 'Equivalence Partitioning'),
    (67, 'Black Box Testing', 'Boundary Value Analysis'),
    (67, 'Black Box Testing', 'Decision Table Testing'),
    (67, 'Black Box Testing', 'State Transition Testing'),
    (67, 'White Box Testing', 'Statement Coverage'),
    (67, 'White Box Testing', 'Branch Coverage'),
    (67, 'White Box Testing', 'Path Testing'),
    (67, 'White Box Testing', 'Control Flow Testing'),
    (67, 'Unit and Integration Testing', 'Unit Testing'),
    (67, 'Unit and Integration Testing', 'Top-Down Integration'),
    (67, 'Unit and Integration Testing', 'Bottom-Up Integration'),
    (67, 'Unit and Integration Testing', 'Stubs and Drivers'),
    (67, 'System and Acceptance Testing', 'System Testing'),
    (67, 'System and Acceptance Testing', 'Acceptance Testing'),
    (67, 'System and Acceptance Testing', 'Alpha Testing'),
    (67, 'System and Acceptance Testing', 'Beta Testing'),
    (67, 'Performance and Security Testing', 'Load Testing'),
    (67, 'Performance and Security Testing', 'Stress Testing'),
    (67, 'Performance and Security Testing', 'Security Testing'),
    (67, 'Performance and Security Testing', 'Usability Testing'),
    (67, 'Test Automation and Test Management', 'Automation Frameworks'),
    (67, 'Test Automation and Test Management', 'Test Scripts'),
    (67, 'Test Automation and Test Management', 'Defect Management'),
    (67, 'Test Automation and Test Management', 'Test Metrics'),
    (70, 'Introduction to Full Stack Development', 'Frontend and Backend Overview'),
    (70, 'Introduction to Full Stack Development', 'Client-Server Architecture'),
    (70, 'Introduction to Full Stack Development', 'Development Environment'),
    (70, 'Introduction to Full Stack Development', 'Version Control'),
    (70, 'HTML and CSS', 'Semantic HTML'),
    (70, 'HTML and CSS', 'Forms and Validation'),
    (70, 'HTML and CSS', 'CSS Layouts'),
    (70, 'HTML and CSS', 'Responsive Web Design'),
    (70, 'JavaScript Fundamentals', 'JavaScript Syntax'),
    (70, 'JavaScript Fundamentals', 'Functions and Scope'),
    (70, 'JavaScript Fundamentals', 'Arrays and Objects'),
    (70, 'JavaScript Fundamentals', 'Asynchronous JavaScript'),
    (70, 'Frontend Frameworks', 'Component-Based Architecture'),
    (70, 'Frontend Frameworks', 'State Management'),
    (70, 'Frontend Frameworks', 'Routing'),
    (70, 'Frontend Frameworks', 'Forms and API Integration'),
    (70, 'Backend Development', 'Server-Side Architecture'),
    (70, 'Backend Development', 'Routing and Middleware'),
    (70, 'Backend Development', 'Business Logic'),
    (70, 'Backend Development', 'Error Handling'),
    (70, 'REST APIs', 'REST Principles'),
    (70, 'REST APIs', 'HTTP Methods and Status Codes'),
    (70, 'REST APIs', 'API Request and Response Design'),
    (70, 'REST APIs', 'API Documentation and Testing'),
    (70, 'Database Integration', 'Relational and NoSQL Databases'),
    (70, 'Database Integration', 'Database Connectivity'),
    (70, 'Database Integration', 'ORM and Query Builders'),
    (70, 'Database Integration', 'Transactions and Data Validation'),
    (70, 'Authentication, Security and Deployment', 'Authentication and Authorization'),
    (70, 'Authentication, Security and Deployment', 'JWT and Session Management'),
    (70, 'Authentication, Security and Deployment', 'Web Application Security'),
    (70, 'Authentication, Security and Deployment', 'Deployment and CI/CD'),
    (90, 'Introduction to Database Systems', 'Database System Concepts'),
    (90, 'Introduction to Database Systems', 'DBMS Architecture'),
    (90, 'Introduction to Database Systems', 'Database Users and Administrators'),
    (90, 'Introduction to Database Systems', 'Advantages of DBMS'),
    (90, 'Data Models and Database Architecture', 'Data Models'),
    (90, 'Data Models and Database Architecture', 'Three-Schema Architecture'),
    (90, 'Data Models and Database Architecture', 'Data Independence'),
    (90, 'Data Models and Database Architecture', 'Database Languages and Interfaces'),
    (90, 'Entity Relationship Model', 'Entities and Attributes'),
    (90, 'Entity Relationship Model', 'Relationships and Constraints'),
    (90, 'Entity Relationship Model', 'ER Diagrams'),
    (90, 'Entity Relationship Model', 'ER to Relational Mapping'),
    (90, 'Relational Model and Relational Algebra', 'Relations and Keys'),
    (90, 'Relational Model and Relational Algebra', 'Integrity Constraints'),
    (90, 'Relational Model and Relational Algebra', 'Relational Algebra Operations'),
    (90, 'Relational Model and Relational Algebra', 'Relational Calculus Basics'),
    (90, 'SQL', 'DDL and DML'),
    (90, 'SQL', 'SELECT Queries'),
    (90, 'SQL', 'Joins and Subqueries'),
    (90, 'SQL', 'Views, Procedures and Triggers'),
    (90, 'Functional Dependencies and Normalization', 'Functional Dependencies'),
    (90, 'Functional Dependencies and Normalization', 'First, Second and Third Normal Forms'),
    (90, 'Functional Dependencies and Normalization', 'BCNF'),
    (90, 'Functional Dependencies and Normalization', 'Decomposition and Dependency Preservation'),
    (90, 'Transactions and Concurrency Control', 'ACID Properties'),
    (90, 'Transactions and Concurrency Control', 'Transaction Schedules and Serializability'),
    (90, 'Transactions and Concurrency Control', 'Lock-Based Concurrency Control'),
    (90, 'Transactions and Concurrency Control', 'Recovery and Deadlocks'),
    (90, 'Indexing, File Organization and Query Processing', 'File Organization'),
    (90, 'Indexing, File Organization and Query Processing', 'B-Tree and B+ Tree Indexing'),
    (90, 'Indexing, File Organization and Query Processing', 'Hash Indexing'),
    (90, 'Indexing, File Organization and Query Processing', 'Query Processing and Optimization')
)
INSERT INTO chapter_topics (chapter_id, topic_name)
SELECT
    sc.id,
    ts.topic_name
FROM topic_seed ts
INNER JOIN subject_chapters sc
    ON sc.subject_id = ts.subject_id
   AND sc.chapter_name = ts.chapter_name
ON CONFLICT (chapter_id, topic_name) DO NOTHING;

COMMIT;

