import type { AdCampaign, AdCreditBalance, AdProduct, CampaignObjective } from "./types";

/**
 * MOCK DATA — Advertise (Creator Studio)
 *
 * Fictional but realistic sample data. Should be replaced by real API
 * responses once the advertising backend is wired up.
 */

export const AD_CREDITS: AdCreditBalance = {
  available: 4200,
  pending: 1800,
  lifetimeFunded: 6000,
};

export const CAMPAIGN_OBJECTIVES: CampaignObjective[] = [
  {
    id: "visibility",
    label: "More Visibility",
    short: "Visibility",
    description: "Increase impressions and marketplace discovery for your product.",
  },
  {
    id: "students",
    label: "More Students",
    short: "Students",
    description: "Optimize toward product visits and enrollments from interested buyers.",
  },
  {
    id: "launch",
    label: "Launch Promotion",
    short: "Launch",
    description: "Give a new test series an initial visibility boost in its first weeks.",
  },
];

export const ELIGIBLE_PRODUCTS: AdProduct[] = [
  {
    id: "p_dsa",
    name: "DSA Placement Test Series",
    kind: "series",
    kindLabel: "Test Series",
    testCount: 12,
    rating: 4.8,
    attempts: 2431,
    price: 299,
    eligible: true,
    recommendedAudience: ["CSE / IT students", "Campus placement aspirants", "3rd & 4th year engineering"],
    tags: ["DSA", "Software", "Placement"],
  },
  {
    id: "p_jee",
    name: "JEE Advanced 2026 Crash Course",
    kind: "course",
    kindLabel: "Course",
    testCount: 18,
    rating: 4.7,
    attempts: 5120,
    price: 1499,
    eligible: true,
    recommendedAudience: ["JEE Advanced", "JEE Main qualifiers", "Class 12 science"],
    tags: ["JEE", "Physics", "Maths"],
  },
  {
    id: "p_neet",
    name: "NEET UG Biology Master Series",
    kind: "series",
    kindLabel: "Test Series",
    testCount: 12,
    rating: 4.9,
    attempts: 2890,
    price: 899,
    eligible: true,
    recommendedAudience: ["NEET UG", "Class 11 & 12 biology", "Medical aspirants"],
    tags: ["NEET", "Biology"],
  },
  {
    id: "p_cat",
    name: "CAT Quant & DILR Sprint",
    kind: "course",
    kindLabel: "Course",
    testCount: 15,
    rating: 4.6,
    attempts: 1620,
    price: 599,
    eligible: true,
    recommendedAudience: ["MBA aspirants", "CAT", "Working professionals"],
    tags: ["CAT", "Quant", "DILR"],
  },
  {
    id: "p_ssc",
    name: "SSC CGL Tier 1 Booster",
    kind: "series",
    kindLabel: "Test Series",
    testCount: 8,
    rating: 4.4,
    attempts: 412,
    price: 699,
    eligible: false,
    recommendedAudience: ["SSC CGL", "Government exam aspirants"],
    tags: ["SSC", "GK"],
  },
  {
    id: "p_bank",
    name: "IBPS PO Prelims Practice",
    kind: "series",
    kindLabel: "Test Series",
    testCount: 10,
    rating: 4.5,
    attempts: 876,
    price: 499,
    eligible: false,
    recommendedAudience: ["Banking", "IBPS PO", "PO prelims"],
    tags: ["Banking", "Reasoning"],
  },
];
export const CAMPAIGNS: AdCampaign[] = [
  {
    id: "c1",
    productId: "p_dsa",
    productName: "DSA Placement Test Series",
    productKindLabel: "Test Series",
    objectiveId: "students",
    status: "active",
    dailyBudget: 300,
    totalBudget: 3000,
    startDate: "2026-08-05",
    endDate: "2026-08-31",
    spent: 1240,
    impressions: 38420,
    reach: 30110,
    clicks: 1284,
    visits: 1284,
    enrollments: 146,
    revenueAttributed: 47254,
    refunds: 3,
    ctrPct: 3.34,
    conversionPct: 11.4,
    costPerEnrollment: 8,
    roas: 3.8,
    createdAt: "2026-08-05",
  },
  {
    id: "c2",
    productId: "p_jee",
    productName: "JEE Advanced 2026 Crash Course",
    productKindLabel: "Course",
    objectiveId: "visibility",
    status: "active",
    dailyBudget: 200,
    totalBudget: 2000,
    startDate: "2026-08-10",
    endDate: "2026-08-30",
    spent: 860,
    impressions: 24120,
    reach: 19830,
    clicks: 692,
    visits: 910,
    enrollments: 74,
    revenueAttributed: 120946,
    refunds: 1,
    ctrPct: 2.87,
    conversionPct: 8.1,
    costPerEnrollment: 11,
    roas: 5.2,
    createdAt: "2026-08-10",
  },
  {
    id: "c3",
    productId: "p_neet",
    productName: "NEET UG Biology Master Series",
    productKindLabel: "Test Series",
    objectiveId: "launch",
    status: "paused",
    dailyBudget: 250,
    totalBudget: 1750,
    startDate: "2026-07-20",
    endDate: "2026-08-18",
    spent: 390,
    impressions: 12240,
    reach: 10110,
    clicks: 318,
    visits: 402,
    enrollments: 42,
    revenueAttributed: 48200,
    refunds: 0,
    ctrPct: 2.56,
    conversionPct: 10.4,
    costPerEnrollment: 9,
    roas: 2.9,
    createdAt: "2026-07-20",
  },
  {
    id: "c4",
    productId: "p_cat",
    productName: "CAT Quant & DILR Sprint",
    productKindLabel: "Course",
    objectiveId: "students",
    status: "completed",
    dailyBudget: 150,
    totalBudget: 2100,
    startDate: "2026-06-01",
    endDate: "2026-06-30",
    spent: 2100,
    impressions: 58100,
    reach: 46200,
    clicks: 1680,
    visits: 1940,
    enrollments: 158,
    revenueAttributed: 94642,
    refunds: 4,
    ctrPct: 2.9,
    conversionPct: 8.2,
    costPerEnrollment: 13,
    roas: 2.4,
    createdAt: "2026-06-01",
  },
  {
    id: "c5",
    productId: "p_ssc",
    productName: "SSC CGL Tier 1 Booster",
    productKindLabel: "Test Series",
    objectiveId: "visibility",
    status: "draft",
    dailyBudget: 100,
    totalBudget: 700,
    startDate: "–",
    endDate: "–",
    spent: 0,
    impressions: 0,
    reach: 0,
    clicks: 0,
    visits: 0,
    enrollments: 0,
    revenueAttributed: 0,
    refunds: 0,
    ctrPct: 0,
    conversionPct: 0,
    costPerEnrollment: 0,
    roas: 0,
    createdAt: "2026-08-18",
  },
];
/** Daily spend series for the active DSA campaign (analytics chart). */
export const DSA_SPEND_SERIES = [
  { date: "2026-08-05", label: "Aug 5", spend: 120, impressions: 3400, clicks: 92 },
  { date: "2026-08-06", label: "Aug 6", spend: 142, impressions: 3920, clicks: 118 },
  { date: "2026-08-07", label: "Aug 7", spend: 134, impressions: 3610, clicks: 101 },
  { date: "2026-08-08", label: "Aug 8", spend: 158, impressions: 4280, clicks: 132 },
  { date: "2026-08-09", label: "Aug 9", spend: 121, impressions: 3100, clicks: 87 },
  { date: "2026-08-10", label: "Aug 10", spend: 172, impressions: 4890, clicks: 154 },
  { date: "2026-08-11", label: "Aug 11", spend: 186, impressions: 5120, clicks: 168 },
  { date: "2026-08-12", label: "Aug 12", spend: 207, impressions: 5700, clicks: 189 },
];

/** Why this creator's DSA product ranks well right now. */
export const VISIBILITY_FACTORS = [
  { label: "Student ratings", strength: 0.95, hint: "4.8 ★ from 1,214 ratings" },
  { label: "Low refund rate", strength: 0.9, hint: "2.1% last 90 days" },
  { label: "High student engagement", strength: 0.88, hint: "Avg 4.6 tests attempted" },
  { label: "Completion / attempt rate", strength: 0.82, hint: "71% completion" },
  { label: "Sales & genuine demand", strength: 0.86, hint: "2,431 attempts · 880 paid" },
  { label: "Product relevance", strength: 0.9, hint: "Matched to placement audience" },
  { label: "Campaign budget", strength: 0.6, hint: "Healthy daily budget" },
];

export const QUALITY_SCORE = 82;